
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip_a:
        default: false
        description: Whether to skip job a
        required: false
        type: boolean
  create:
  pull_request:
  push:

jobs:
  prebuild-a:
    if: inputs.skip_a != true
    uses: ./.github/workflows/build-a.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build-staging:
    needs: [test, prebuild-a]
    if: always() && !cancelled() && github.ref_name == 'staging' && needs.test.result == 'success' && (needs.prebuild-a.result == 'success' || needs.prebuild-a.result == 'skipped')
    uses: ./.github/workflows/build-b.yml
    secrets: inherit

  build-production:
    needs: [test, prebuild-a]
    if: always() && !cancelled() && github.ref_name == 'main' && needs.test.result == 'success' && (needs.prebuild-a.result == 'success' || needs.prebuild-a.result == 'skipped')
    uses: ./.github/workflows/build-b.yml
    secrets: inherit

  deploy-staging:
    needs: [build-staging]
    if: github.ref_name == 'staging'
    # if: always() && !cancelled() && needs.build-production == 'success'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  deploy-production:
    needs: [build-production]
    if: github.ref_name == 'production'
    # if: always() && !cancelled() && needs.build-production == 'success'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
